const ids = require('../../ids/ids');
const time = require('../time-converter');

module.exports = [
    {
        _id: ids.place_dz_nbg,
        name: 'Dom zdravlja NBG',
        address: 'Adresa NBG',
        description: '',
        workingHours: '09:00-17:00',
        date: '',
        isStatic: true,
        geolocation: ids.beograd,
    },
    {
        _id: ids.place_dz_vracar,
        name: 'Dom zdravlja Vracar',
        address: 'Adresa Vracar',
        description: '',
        workingHours: '09:00-17:00',
        date: '',
        isStatic: true,
        geolocation: ids.beograd,
    },
    {
        _id: ids.place_dz_zemun,
        name: 'Dom zdravlja NBG',
        address: 'Adresa Zemun',
        description: '',
        workingHours: '09:00-17:00',
        date: '',
        isStatic: true,
        geolocation: ids.beograd,
    },
    {
        _id: ids.place_kc_bg,
        name: 'Klinicki Centar Beograd',
        address: 'Adresa KC BGD',
        description: '',
        workingHours: '09:00-17:00',
        date: '',
        isStatic: true,
        geolocation: ids.beograd,
    },
    {
        _id: ids.place_kc_nis,
        name: 'Klinicki Centar Nis',
        address: 'Adresa Nis',
        description: '',
        workingHours: '09:00-17:00',
        date: '',
        isStatic: true,
        geolocation: ids.nis,
    },
    {
        _id: ids.place_dz_cuprija,
        name: 'Dom zdravlja Cuprija',
        address: 'Adresa Cuprija',
        description: '',
        workingHours: '09:00-17:00',
        date: '',
        isStatic: true,
        geolocation: ids.cuprija,
    },
    {
        _id: ids.place_karavan_bg,
        name: 'Karavan na trgu batooo',
        address: 'Adresa Karavan',
        description: '',
        workingHours: '09:00-17:00',
        date: time(7, '+'),
        isStatic: false,
        geolocation: ids.beograd,
    },
];
